---
openapi: 3.0.1
info:
    title: ${title}
    description: ${description}
    version: 0.0.8
servers:
    - url: "/"
security:
    - ApiKey: []
paths:
    "/list":
        get:
            description: returns items in the list
            parameters:
                - name: from
                  in: query
                  description: get items from this offset
                  required: false
                  schema:
                      type: string
                - name: limit
                  in: query
                  description: limits the number of items returned
                  schema:
                      type: integer
                      default: 25
            security:
                - ApiKey: []
            responses:
                "200":
                    description: successfully returned items in the list
                    content:
                        "application/json":
                            schema:
                              type: object
                              required:
                                  - items
                              properties:
                                  next:
                                      type: string
                                  items:
                                      type: array
                                      items:
                                          "$ref": "#/components/schemas/Item"
                "401":
                    "$ref": "#/definitions/NoApiKey"
                "413":
                    description: too many items requested
                    content: {}
            x-amazon-apigateway-integration:
                httpMethod: POST
                passthroughBehavior: when_no_templates
                type: aws_proxy
                uri: "${list_get_uri}"
        put:
            description: replaces an item in the list
            requestBody:
                content:
                    "application/json":
                        schema:
                            "$ref": "#/components/schemas/PartialItem"
                required: false
            security:
                - ApiKey: []
            responses:
                "200":
                    description: replacement was successful
                    content:
                        "application/json":
                            schema:
                                    "$ref": "#/components/schemas/Item"
                "401":
                    "$ref": "#/definitions/NoApiKey"
                "403":
                    description: the item is invalid
                    content: {}
                "404":
                    description: the item being replaced was not found
                    content: {}
            x-amazon-apigateway-integration:
                httpMethod: POST
                passthroughBehavior: when_no_templates
                type: aws_proxy
                uri: "${list_put_uri}"
        post:
            description: adds an item to the list
            requestBody:
                content:
                    "application/json":
                        schema:
                            "$ref": "#/components/schemas/ItemPrototype"
                required: true
            security:
                - ApiKey: []
            responses:
                "200":
                    description: item successfully added
                    content:
                        "application/json":
                            schema:
                                "$ref": "#/components/schemas/Item"
                "401":
                    "$ref": "#/definitions/NoApiKey"
                "403":
                    description: the partial items was invalid
                    content: {}
            x-amazon-apigateway-integration:
                httpMethod: POST
                passthroughBehavior: when_no_templates
                type: aws_proxy
                uri: "${list_post_uri}"
        delete:
            description: removes an item in the list
            parameters:
                - name: item
                  in: query
                  schema:
                      type: string
            security:
                - ApiKey: []
            responses:
                "200":
                    description: item successfully removed
                    content:
                      "application/json":
                        schema:
                          "$ref": "#/components/schemas/Item"
                "401":
                    "$ref": "#/definitions/NoApiKey"
                "404":
                    description: no item found to delete
                    content: {}
            x-amazon-apigateway-integration:
                httpMethod: POST
                passthroughBehavior: when_no_templates
                type: aws_proxy
                uri: "${list_delete_uri}"
    "/report":
        get:
            description: returns a report on the list over a given period
            security:
                - ApiKey: []
            responses:
                "401":
                    "$ref": "#/definitions/NoApiKey"
                "501":
                    description: not implemented in this version
                    content: {}
            x-amazon-apigateway-integration:
                httpMethod: POST
                passthroughBehavior: when_no_templates
                type: aws_proxy
                uri: "${report_get_uri}"
components:
    schemas:
        Item:
            required:
                - id
                - name
                - quantity
            type: object
            properties:
                id:
                    type: string
                name:
                    type: string
                quantity:
                    type: integer
        ItemPrototype:
            required:
                - name
                - quantity
            type: object
            properties:
                name:
                    type: string
                quantity:
                    type: integer
        PartialItem:
            required:
                - id
            type: object
            properties:
                id:
                    type: string
                name:
                    type: string
                quantity:
                    type: integer
        NoApiKey:
            type: object
            description: a valid api key was not provided
    securitySchemes:
        ApiKey:
            type: apiKey
            name: x-api-key
            in: header
x-amazon-apigateway-request-validators:
    both:
        validateRequestBody: true
        validateRequestParameters: true
x-amazon-apigateway-api-key-source: HEADER
x-amazon-apigateway-request-validator: both
